title: Rylocadrem
email: rylocadrem@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Un blog pour exposer mes réflexions sur les sectes, la rationalité, la science, la Bible...
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://rylocadrem.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: #
# github_username:  rylocadrem
lang: fr

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Markdown processing
markdown: kramdown
kramdown:
  toc_levels: 1..3
#   parse_block_html: true

# Minima theme
author: rylocadrem
show_excerpts: true
minima:
  date_format: "%d/%m/%Y"

# Categories
collections:
  breves:
    output: true
    permalink: /bref/:name
  categories:
    output: true
    permalink: /categories/:name

# Analytics
google_analytics: UA-71616950-5