title: Rylocadrem
email: rylocadrem@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Un blog de réflexions sur les sectes, la rationalité et la pensée critique.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://rylocadrem.github.io/blog" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: #
# github_username:  rylocadrem

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Markdown processing
# kramdown:
#   -

# Minima theme
show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
